name: Display Current Date and Time

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  show-datetime:
    name: Print Current Date/Time
    runs-on: ubuntu-latest
    steps:
    - name: Display date and time
      run: |
        echo "Current date and time: $(date)"
