name: DateTime
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
jobs:
  display-datetime:
    name: Display current date and time
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Print current date and time
      run: |
        echo "Current date and time: $(date)"
